name: Embed code in README
on:
  pull_request:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
            # Optional, defaults to author of the commit that triggered the run
            commit_author: Samir Araujo <samir.araujo@gmail.com>
        
            # Optional, defaults to "actions@github.com"
            commit_user_email: samir.araujo@gmail.com
        
            # Optional, but recommended
            # Defaults to "Apply automatic changes"
            commit_message: Apply automatic changes
        
            # Optional branch name where commit should be pushed to.
            # Defaults to the current branch.
            #branch: feature-123
        
            # Optional output file paths, defaults to '[./README.md]'.
            output_file_paths: '[./TABLE.md]'
        
            # Categories to automatically sync or transform its contents in the markdown files.
            # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
            categories: '[code-block,json-to-html-table,workflow-artifact-table]'
